module.exports.badRequestErrorCode = 400;
module.exports.badRequestErrorMessage = { message: 'Переданы некорректные данные' };
module.exports.unauthorizedErrorCode = 401;
module.exports.unauthorizedErrorMessage = { message: 'Необходима авторизация' };
module.exports.notFoundErrorCode = 404;
module.exports.notFoundErrorMessage = { message: 'Данные не найдены' };
module.exports.serverErrorCode = 500;
module.exports.serverErrorMessage = { message: 'Произошла ошибка' };
module.exports.URL_REGEXP = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)/;
module.exports.JWT_SECRET = 'a7d0e128f6ac25bc040ba4460a58328f82f5c8c314f3b4f95a086c81cecd7175';
